export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_MESSAGE = 'FETCH_MESSAGE';

// TODOS
export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_PENDING = 'FETCH_TODOS_PENDING';
export const FETCH_TODOS_FULFILLED = 'FETCH_TODOS_FULFILLED';
export const FETCH_TODOS_REJECTED = 'FETCH_TODOS_REJECTED';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_PENDING = 'ADD_TODO_PENDING';
export const ADD_TODO_FULFILLED = 'ADD_TODO_FULFILLED';
export const ADD_TODO_REJECTED = 'ADD_TODO_REJECTED';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_PENDING = 'UPDATE_TODO_PENDING';
export const UPDATE_TODO_FULFILLED = 'UPDATE_TODO_FULFILLED';
export const UPDATE_TODO_REJECTED = 'UPDATE_TODO_REJECTED';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_PENDING = 'DELETE_TODO_PENDING';
export const DELETE_TODO_FULFILLED = 'DELETE_TODO_FULFILLED';
export const DELETE_TODO_REJECTED = 'DELETE_TODO_REJECTED';
